#!/usr/bin/env python3
##
## EPITECH PROJECT, 2022
## 209poll
## File description:
## main
##

from calc_209 import *
import sys

def man_help():
    print("USAGE")
    print("\t./209poll pSize sSize p")
    print("DESCRIPTION")
    print("\tpSize\tsize of the population")
    print("\tsSize\tsize of the sample (supposed to be representative)")
    print("\tp\tpercentage of voting intentions for a specific candidate")

def main():
    if (len(sys.argv) == 2 and sys.argv[1] == "-h"):
        man_help()
        exit(0)
    if (len(sys.argv) != 4):
        exit(84)
    if (int(sys.argv[1]) < 0):
        exit(84)
    calc_209(int(sys.argv[1]), int(sys.argv[2]), float(sys.argv[3]))

try:
    if __name__ == '__main__':
        main()
except Exception as error:
    print(error, file = sys.stderr)
    exit(84)